from utilities import (add,subtract,multiply,divide,reverse_string,to_uppercase,to_lowercase,is_palindrome,get_current_date,get_current_time,get_current_datetime)
print("Math utilities:")
print ("Addition: ",add(10,5))
print ("Subtraction: ",subtract(10,5))
print ("Multiplication: ",multiply(10,5))
print ("Division: ",divide(10,5))
print("\nString utilities:")
print ("Reverse:",reverse_string("Python"))
print("Uppercase:",to_uppercase("Python"))
print("Lowercase:",to_lowercase("Python"))
print("Palindrome:",is_palindrome("madam"))
print("\nDate utilities:")
print("Current date:",get_current_date())
print("Current time:",get_current_time())
print("Current Date and time:",get_current_datetime())